<a href="https://colab.research.google.com/github/ClaudionorPeixinho/CanaOnline/blob/main/Univesp_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


importar a biblioteca Numpy

In [45]:
import numpy as np

In [46]:
dados=np.random.rand(2,3)

In [47]:
dados

array([[0.68263599, 0.38289738, 0.0376028 ],
       [0.51209142, 0.83434675, 0.8234528 ]])

Tipo de Array

In [48]:
dados.dtype

dtype('float64')

Tamanho e Quantidade de dimensões


In [49]:
dados.shape

(2, 3)

In [50]:
lista=[1,2,5,7.8,1.25]



In [51]:
dados2=np.array(lista)

In [52]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [53]:
lista2=[[1,2,3,4],[4,3,2,1]]

In [54]:
dados3=np.array(lista2)

In [55]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

Criando uma NDarray

In [56]:
dados=np.random.rand(2,3)

In [57]:
dados

array([[0.32051267, 0.44945738, 0.51273019],
       [0.66964812, 0.19823127, 0.72003734]])

In [58]:
dados.dtype

dtype('float64')

In [59]:
dados.shape

(2, 3)

In [60]:
dados.ndim

2

In [61]:
lista=[1,2,5,7.8,1.25]

In [62]:
dados2=np.array(lista)

In [63]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

Criar uma lista com duas dimensões

In [64]:
lista2=[[1,2,3,4],[4,3,2,1]]

In [65]:
dados3=np.array(lista2)

In [66]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [67]:
dadoszero=np.zeros(25)

In [68]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
dadosum=np.ones(10)

In [70]:
dadosum

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
dadosseq=np.arange(10)

In [72]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
dadosseq2=np.arange(0,20,2)

In [74]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [75]:
dadosseq.dtype

dtype('int64')

In [76]:
dadosseqf=dadosseq.astype(np.float64)

In [77]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Aritmeticas com arrays

In [78]:
dados4=np.array([[1,2,3],[4,5,6]])

In [79]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
dados4=np.array([[1,2,3,4],[5,6,7,8]])

In [81]:
dados4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])